name: hello_world
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.1.0
  table_calendar: ^3.1.3
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  rive: 0.13.20
  flutter_map: ^7.0.2
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/RiveAssets/
    - assets/images/